# https://projecteuler.net/problem=45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle
# Tₙ=n(n+1)/2
# 1, 3, 6, 10, 15, ...
# Pentagonal
# Pₙ=n(3n−1)/2
# 1, 5, 12, 22, 35, ...
# Hexagonal
# Hₙ=n(2n−1)
# 1, 6, 15, 28, 45, ...
# It can be verified that T₂₈₅ = P₁₆₅ = H₁₄₃ = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
#
# https://euler.jakumo.org/problems/view/45.html
# Треугольные, пятиугольные и шестиугольные числа вычисляются по нижеследующим формулам:
# Треугольные
# Tₙ=n(n+1)/2
# 1, 3, 6, 10, 15, ...
# Пятиугольные
# Pₙ=n(3n−1)/2
# 1, 5, 12, 22, 35, ...
# Шестиугольные
# Hₙ=n(2n−1)
# 1, 6, 15, 28, 45, ...
# Можно убедиться в том, что T₂₈₅ = P₁₆₅ = H₁₄₃ = 40755.
# Найдите следующее треугольное число, являющееся также пятиугольным и шестиугольным.
#
# 1533776805

import math
import time

start_time = time.time()

def n(a, b, c):
    x1 = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
    if x1 % 1 == 0:
        return True
    else:
        return False


m = 40756

while True:
    if m % 1000000 == 0:
        print(">", f'{m:,}'.replace(',', ' '))
    # if n(1, 1, -2 * m) and n(3, -1, -2 * m) and n(2, -1, -m):
    if n(1, 1, -2 * m) and n(3, -1, -2 * m) and n(2, -1, -m):
        print(m)
        break
    m += 1

end_time = time.time()

print()
print('time:', end_time - start_time)
